definitions:
  main.GetBalance.getBalanceResponse:
    properties:
      balance:
        example: "1000000000"
        type: string
    type: object
info:
  contact: {}
paths:
  /eth/balance/{address}:
    get:
      consumes:
      - application/json
      description: Get the Ethereum balance for the given address
      parameters:
      - description: Ethereum Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.GetBalance.getBalanceResponse'
        "400":
          description: Invalid address
          schema:
            type: string
        "500":
          description: Failed to get balance
          schema:
            type: string
  /healthy:
    get:
      consumes:
      - application/json
      description: Show the health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
  /ready:
    get:
      consumes:
      - application/json
      description: Show the readiness status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "503":
          description: Service not ready
          schema:
            type: string
swagger: "2.0"
